# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]

joint_limits:
  A_joint:
    has_velocity_limits: true
    max_velocity: 4.4
    has_acceleration_limits: true
    max_acceleration: 2.0 # rad/s^2 (how fast the joint can speed up)
  B_joint:
    has_velocity_limits: true
    max_velocity: 3.0   # rad/s
    has_acceleration_limits: true
    max_acceleration: 1.5
  C_joint:
    has_velocity_limits: true
    max_velocity: 3.0
    has_acceleration_limits: true
    max_acceleration: 1.5
  Left_jaw_joint:
    has_velocity_limits: true
    max_velocity: 10.0
    has_acceleration_limits: true
    max_acceleration: 5.0
  Right_jaw_joint:
    has_velocity_limits: true
    max_velocity: 10.0
    has_acceleration_limits: true
    max_acceleration: 5.0
  X_joint:
    has_velocity_limits: true
    max_velocity: 15.0
    has_acceleration_limits: true
    max_acceleration: 7.0
  Y_joint:
    has_velocity_limits: true
    max_velocity: 1.4
    has_acceleration_limits: true
    max_acceleration: 0.7
  Z_joint:
    has_velocity_limits: true
    max_velocity: 1.4
    has_acceleration_limits: true
    max_acceleration: 0.7

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1