# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_controller
    - gripper_controller

  arm_controller:
    type: FollowJointTrajectory
    joints:
      - X_joint
      - Y_joint
      - Z_joint
      - A_joint
      - B_joint
      - C_joint
    action_ns: follow_joint_trajectory
    default: true
    
  gripper_controller:
    type: FollowJointTrajectory
    # type: GripperCommand
    joints:
      - Right_jaw_joint
      # - Left_jaw_joint
    # action_ns: gripper_cmd
    action_ns: follow_joint_trajectory
    default: true

trajectory_execution:
  allowed_execution_duration_scaling: 2.5  # Allow 2x the planned time
  allowed_goal_duration_margin: 1.5        # Allow 0.5s extra at the end
  allowed_start_tolerance: 0.02          # Allow 0.01 rad tolerance at start
  stop_on_goal_failure: false
  # execution_duration_monitoring: false
  execution_duration_monitoring: true
  # wait_for_trajectory_completion: true
  wait_for_trajectory_completion: false