move_group:
  ros__parameters:
    planning_pipelines:
      move_group:
        planner_plugins:
          - ompl_interface/OMPLPlanner
    default_planner_config: ompl_interface/OMPLPlanner
    request_adapters: >
      default_planner_request_adapters/AddTimeOptimalParameterization
      default_planner_request_adapters/FixWorkspaceBounds
      default_planner_request_adapters/FixStartStateBounds
      default_planner_request_adapters/FixStartStateCollision
      default_planner_request_adapters/FixStartStatePathConstraints
    start_state_max_bounds_error: 0.1
